import React, { useState, useEffect } from "react";
import { api } from "../services/api";
import {
  Users,
  Key,
  ShieldCheck,
  Copy,
  Check,
  Info,
  Loader,
  AlertTriangle,
  Trash2,
} from "lucide-react";

export function ClientAdmin() {
  const [formData, setFormData] = useState({
    username: "",
    email: "",
    company: "",
  });
  const [clients, setClients] = useState([]);
  const [isLoading, setIsLoading] = useState(false);
  const [isSubmitting, setIsSubmitting] = useState(false);
  const [error, setError] = useState("");
  const [success, setSuccess] = useState("");

  // Persisted credentials history in LocalStorage
  const [history, setHistory] = useState(() => {
    try {
      const stored = localStorage.getItem("relay_generated_clients");
      return stored ? JSON.parse(stored) : [];
    } catch (e) {
      return [];
    }
  });

  // Keep track of copied states for individual fields ('e-id' or 'p-id')
  const [copiedStates, setCopiedStates] = useState({});

  const fetchClients = async () => {
    setIsLoading(true);
    try {
      // Safely check if getUsers exists on api, otherwise fallback to api.get
      let data;
      if (typeof api.getUsers === "function") {
        data = await api.getUsers({ role: "Executive / Auditor" });
      } else {
        const response = await api.get("/users?role=Executive / Auditor");
        data = response.data || response;
      }
      setClients(Array.isArray(data) ? data : []);
    } catch (err) {
      console.error("Failed to fetch clients:", err);
    } finally {
      setIsLoading(false);
    }
  };

  useEffect(() => {
    fetchClients();
  }, []);

  const handleChange = (e) => {
    setError("");
    setFormData((prev) => ({
      ...prev,
      [e.target.name]: e.target.value,
    }));
  };

  const handleInlineCopy = (text, key) => {
    navigator.clipboard.writeText(text);
    setCopiedStates((prev) => ({ ...prev, [key]: true }));
    setTimeout(() => {
      setCopiedStates((prev) => ({ ...prev, [key]: false }));
    }, 2000);
  };

  const handleSubmit = async (e) => {
    e.preventDefault();
    setIsSubmitting(true);
    setError("");
    setSuccess("");

    try {
      // Use api.post directly with a plain JavaScript object
      const response = await api.post("/auth/register-client", {
        username: formData.username.trim(),
        email: formData.email.trim(),
        company: formData.company.trim() || undefined,
      });

      // Axios returns the server response body inside response.data
      const resData = response?.data || response;

      setSuccess("Client registered successfully!");

      // Save credentials to local storage log
      const newLog = {
        id: resData.user?.id || Date.now(),
        username: resData.user?.username || formData.username,
        email: resData.user?.email || formData.email,
        password: resData.password || "Generated by server",
        company: resData.user?.company || formData.company || "—",
        timestamp: new Date().toLocaleString(),
      };

      setHistory((prev) => {
        const updated = [newLog, ...prev];
        localStorage.setItem(
          "relay_generated_clients",
          JSON.stringify(updated),
        );
        return updated;
      });

      // Reset form
      setFormData({
        username: "",
        email: "",
        company: "",
      });

      // Refresh client list
      fetchClients();
    } catch (err) {
      const errorMsg =
        err.response?.data?.message ||
        err.message ||
        "Failed to register client user.";
      setError(errorMsg);
    } finally {
      setIsSubmitting(false);
    }
  };

  const handleClearHistory = () => {
    if (
      window.confirm(
        "Are you sure you want to clear the generated credentials history?",
      )
    ) {
      localStorage.removeItem("relay_generated_clients");
      setHistory([]);
    }
  };

  const handleDeleteUser = async (userId, username) => {
    if (
      !window.confirm(
        `Are you sure you want to permanently delete the client user "${username}"?`,
      )
    ) {
      return;
    }

    try {
      if (typeof api.deleteUser === "function") {
        await api.deleteUser(userId);
      } else {
        await api.delete(`/users/${userId}`);
      }

      fetchClients();

      // Clean up deleted user from local history
      setHistory((prev) => {
        const updated = prev.filter((item) => item.id !== userId);
        localStorage.setItem(
          "relay_generated_clients",
          JSON.stringify(updated),
        );
        return updated;
      });
    } catch (err) {
      const errorMsg =
        err.response?.data?.message ||
        err.message ||
        "Failed to delete client user.";
      alert(errorMsg);
    }
  };

  return (
    <div
      className="client-admin-page"
      style={{
        display: "grid",
        gridTemplateColumns: "1.1fr 1.3fr",
        gap: "24px",
        alignItems: "start",
      }}
    >
      <div style={{ display: "flex", flexDirection: "column", gap: "24px" }}>
        {/* Client Registration Card */}
        <div
          className="card"
          style={{
            padding: "24px",
            background: "var(--panel)",
            border: "1px solid var(--line)",
            borderRadius: "12px",
          }}
        >
          <div
            style={{
              display: "flex",
              alignItems: "center",
              gap: "10px",
              marginBottom: "20px",
            }}
          >
            <div
              style={{
                padding: "8px",
                background: "rgba(245, 158, 11, 0.15)",
                borderRadius: "8px",
                color: "var(--amber)",
              }}
            >
              <Key size={20} />
            </div>
            <div>
              <h2 style={{ fontSize: "18px", fontWeight: "600", margin: 0 }}>
                Register New Client
              </h2>
              <p
                className="faint"
                style={{ fontSize: "12px", margin: "2px 0 0" }}
              >
                Autogenerate access and send welcome email
              </p>
            </div>
          </div>

          {error && (
            <div
              className="auth-error"
              style={{
                marginBottom: "16px",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                color: "var(--rose)",
                background: "rgba(225, 29, 72, 0.1)",
                padding: "10px",
                borderRadius: "8px",
                fontSize: "13px",
              }}
            >
              <AlertTriangle size={16} />
              {error}
            </div>
          )}

          {success && (
            <div
              style={{
                marginBottom: "16px",
                display: "flex",
                alignItems: "center",
                gap: "8px",
                color: "var(--teal)",
                background: "rgba(20, 184, 166, 0.1)",
                padding: "10px",
                borderRadius: "8px",
                fontSize: "13px",
              }}
            >
              <ShieldCheck size={16} />
              {success}
            </div>
          )}

          <form
            onSubmit={handleSubmit}
            style={{ display: "flex", flexDirection: "column", gap: "16px" }}
          >
            <div className="form-group">
              <label
                className="form-label"
                style={{
                  display: "block",
                  fontSize: "12px",
                  fontWeight: "500",
                  marginBottom: "6px",
                  color: "var(--muted)",
                }}
              >
                Client Username / Contact Name
              </label>
              <input
                type="text"
                name="username"
                className="form-input"
                placeholder="e.g. John Doe"
                value={formData.username}
                onChange={handleChange}
                required
                style={{
                  width: "100%",
                  padding: "10px",
                  borderRadius: "8px",
                  background: "var(--bg)",
                  border: "1px solid var(--line2)",
                  color: "var(--ink)",
                }}
              />
            </div>

            <div className="form-group">
              <label
                className="form-label"
                style={{
                  display: "block",
                  fontSize: "12px",
                  fontWeight: "500",
                  marginBottom: "6px",
                  color: "var(--muted)",
                }}
              >
                Client Email (for Login & Delivery)
              </label>
              <input
                type="email"
                name="email"
                className="form-input"
                placeholder="client@company.com"
                value={formData.email}
                onChange={handleChange}
                required
                style={{
                  width: "100%",
                  padding: "10px",
                  borderRadius: "8px",
                  background: "var(--bg)",
                  border: "1px solid var(--line2)",
                  color: "var(--ink)",
                }}
              />
            </div>

            <div className="form-group">
              <label
                className="form-label"
                style={{
                  display: "block",
                  fontSize: "12px",
                  fontWeight: "500",
                  marginBottom: "6px",
                  color: "var(--muted)",
                }}
              >
                Company Name
              </label>
              <input
                type="text"
                name="company"
                className="form-input"
                placeholder="e.g. Oaknet Business"
                value={formData.company}
                onChange={handleChange}
                style={{
                  width: "100%",
                  padding: "10px",
                  borderRadius: "8px",
                  background: "var(--bg)",
                  border: "1px solid var(--line2)",
                  color: "var(--ink)",
                }}
              />
            </div>

            <button
              type="submit"
              className="submit-btn"
              disabled={isSubmitting || !formData.username || !formData.email}
              style={{
                marginTop: "8px",
                padding: "12px",
                borderRadius: "8px",
                background:
                  "linear-gradient(135deg, var(--amber), var(--amber2))",
                color: "#06111f",
                fontWeight: "600",
                border: "none",
                cursor: "pointer",
                display: "flex",
                alignItems: "center",
                justifyContent: "center",
                gap: "8px",
              }}
            >
              {isSubmitting
                ? "Sending credentials email..."
                : "Create Client & Send Password"}
            </button>
          </form>
        </div>

        {/* Persisted Credentials History Log */}
        <div
          className="card"
          style={{
            padding: "24px",
            background: "var(--panel)",
            border: "1px solid var(--line)",
            borderRadius: "12px",
          }}
        >
          <div
            style={{
              display: "flex",
              justifyContent: "space-between",
              alignItems: "center",
              marginBottom: "16px",
            }}
          >
            <div>
              <h3 style={{ fontSize: "14px", fontWeight: "600", margin: 0 }}>
                Generated Credentials History
              </h3>
              <p
                className="faint"
                style={{ fontSize: "11px", margin: "2px 0 0" }}
              >
                Stored locally in this browser
              </p>
            </div>
            {history.length > 0 && (
              <button
                onClick={handleClearHistory}
                style={{
                  background: "transparent",
                  border: "none",
                  color: "var(--rose)",
                  fontSize: "11px",
                  cursor: "pointer",
                  padding: "4px 8px",
                  borderRadius: "4px",
                }}
              >
                Clear History
              </button>
            )}
          </div>

          {history.length === 0 ? (
            <div
              style={{
                padding: "20px 0",
                textAlign: "center",
                color: "var(--muted)",
                fontSize: "12px",
                border: "1px dashed var(--line2)",
                borderRadius: "8px",
              }}
            >
              No recently generated credentials.
            </div>
          ) : (
            <div
              style={{
                display: "flex",
                flexDirection: "column",
                gap: "12px",
                maxHeight: "350px",
                overflowY: "auto",
                paddingRight: "4px",
              }}
            >
              {history.map((item, idx) => (
                <div
                  key={item.id || idx}
                  style={{
                    padding: "12px",
                    background: "var(--panel2)",
                    border: "1px solid var(--line2)",
                    borderRadius: "8px",
                    fontSize: "11.5px",
                    position: "relative",
                  }}
                >
                  <div
                    style={{
                      display: "flex",
                      justifyContent: "space-between",
                      marginBottom: "8px",
                      borderBottom: "1px solid var(--line)",
                      paddingBottom: "4px",
                    }}
                  >
                    <span style={{ fontWeight: "600", color: "var(--ink)" }}>
                      {item.username} ({item.company})
                    </span>
                    <span className="faint" style={{ fontSize: "10px" }}>
                      {item.timestamp}
                    </span>
                  </div>
                  <div
                    style={{
                      display: "flex",
                      flexDirection: "column",
                      gap: "4px",
                      fontFamily: "var(--mono)",
                    }}
                  >
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                      }}
                    >
                      <span>
                        Email:{" "}
                        <span style={{ color: "var(--ink)" }}>
                          {item.email}
                        </span>
                      </span>
                      <button
                        onClick={() =>
                          handleInlineCopy(item.email, `e-${item.id}`)
                        }
                        style={{
                          background: "none",
                          border: "none",
                          cursor: "pointer",
                          color: "var(--muted)",
                        }}
                      >
                        {copiedStates[`e-${item.id}`] ? (
                          <Check size={11} style={{ color: "var(--teal)" }} />
                        ) : (
                          <Copy size={11} />
                        )}
                      </button>
                    </div>
                    <div
                      style={{
                        display: "flex",
                        justifyContent: "space-between",
                        alignItems: "center",
                      }}
                    >
                      <span>
                        Password:{" "}
                        <span
                          style={{ color: "var(--amber)", fontWeight: "600" }}
                        >
                          {item.password}
                        </span>
                      </span>
                      <button
                        onClick={() =>
                          handleInlineCopy(item.password, `p-${item.id}`)
                        }
                        style={{
                          background: "none",
                          border: "none",
                          cursor: "pointer",
                          color: "var(--muted)",
                        }}
                      >
                        {copiedStates[`p-${item.id}`] ? (
                          <Check size={11} style={{ color: "var(--teal)" }} />
                        ) : (
                          <Copy size={11} />
                        )}
                      </button>
                    </div>
                  </div>
                </div>
              ))}
            </div>
          )}
        </div>
      </div>

      {/* Existing Clients List */}
      <div
        className="card"
        style={{
          padding: "24px",
          background: "var(--panel)",
          border: "1px solid var(--line)",
          borderRadius: "12px",
          height: "100%",
        }}
      >
        <div
          style={{
            display: "flex",
            alignItems: "center",
            gap: "10px",
            marginBottom: "20px",
          }}
        >
          <div
            style={{
              padding: "8px",
              background: "rgba(20, 184, 166, 0.15)",
              borderRadius: "8px",
              color: "var(--teal)",
            }}
          >
            <Users size={20} />
          </div>
          <div>
            <h2 style={{ fontSize: "18px", fontWeight: "600", margin: 0 }}>
              Active Client Accounts
            </h2>
            <p
              className="faint"
              style={{ fontSize: "12px", margin: "2px 0 0" }}
            >
              Registered read-only client profiles
            </p>
          </div>
        </div>

        {isLoading ? (
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              height: "200px",
              gap: "12px",
            }}
          >
            <Loader
              size={24}
              className="spin"
              style={{ color: "var(--teal)" }}
            />
            <span style={{ fontSize: "12px", color: "var(--muted)" }}>
              Fetching accounts...
            </span>
          </div>
        ) : clients.length === 0 ? (
          <div
            style={{
              display: "flex",
              flexDirection: "column",
              alignItems: "center",
              justifyContent: "center",
              height: "200px",
              border: "1px dashed var(--line2)",
              borderRadius: "8px",
              color: "var(--faint)",
            }}
          >
            <Users size={32} style={{ marginBottom: "8px" }} />
            <span style={{ fontSize: "13px" }}>
              No client users registered yet.
            </span>
          </div>
        ) : (
          <div style={{ overflowX: "auto" }}>
            <table
              style={{
                width: "100%",
                borderCollapse: "collapse",
                textAlign: "left",
                fontSize: "13px",
              }}
            >
              <thead>
                <tr style={{ borderBottom: "1px solid var(--line2)" }}>
                  <th
                    style={{
                      padding: "10px 8px",
                      fontWeight: "500",
                      color: "var(--muted)",
                    }}
                  >
                    Name
                  </th>
                  <th
                    style={{
                      padding: "10px 8px",
                      fontWeight: "500",
                      color: "var(--muted)",
                    }}
                  >
                    Email
                  </th>
                  <th
                    style={{
                      padding: "10px 8px",
                      fontWeight: "500",
                      color: "var(--muted)",
                    }}
                  >
                    Company
                  </th>
                  <th
                    style={{
                      padding: "10px 8px",
                      fontWeight: "500",
                      color: "var(--muted)",
                    }}
                  >
                    Status
                  </th>
                  <th
                    style={{
                      padding: "10px 8px",
                      fontWeight: "500",
                      color: "var(--muted)",
                      textAlign: "right",
                    }}
                  >
                    Actions
                  </th>
                </tr>
              </thead>
              <tbody>
                {clients.map((client) => (
                  <tr
                    key={client.id}
                    style={{
                      borderBottom: "1px solid var(--line)",
                      transition: "background-color 0.1s",
                    }}
                    className="table-row-hover"
                  >
                    <td
                      style={{
                        padding: "12px 8px",
                        fontWeight: "500",
                        color: "var(--ink)",
                      }}
                    >
                      {client.first_name || client.username}
                    </td>
                    <td
                      style={{
                        padding: "12px 8px",
                        color: "var(--muted)",
                        fontFamily: "var(--mono)",
                        fontSize: "12px",
                      }}
                    >
                      {client.email}
                    </td>
                    <td style={{ padding: "12px 8px", color: "var(--muted)" }}>
                      {client.company || "—"}
                    </td>
                    <td style={{ padding: "12px 8px" }}>
                      <span
                        style={{
                          fontSize: "11px",
                          padding: "2px 8px",
                          borderRadius: "12px",
                          background: "rgba(20, 184, 166, 0.12)",
                          color: "var(--teal)",
                          fontWeight: "500",
                        }}
                      >
                        {client.status || "Active"}
                      </span>
                    </td>
                    <td style={{ padding: "12px 8px", textAlign: "right" }}>
                      <button
                        onClick={() =>
                          handleDeleteUser(
                            client.id,
                            client.first_name || client.username,
                          )
                        }
                        style={{
                          background: "transparent",
                          border: "none",
                          color: "var(--rose)",
                          cursor: "pointer",
                          padding: "4px",
                          borderRadius: "4px",
                          display: "inline-flex",
                          alignItems: "center",
                          justifyContent: "center",
                          transition: "opacity 0.15s",
                        }}
                        title={`Delete ${client.first_name || client.username}`}
                        className="table-delete-btn"
                      >
                        <Trash2 size={15} />
                      </button>
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </div>
    </div>
  );
}
